replicaCount: 1

releaseName: react-site
namespace: prod

image:
  repository: danielmak1/d3v0ps
  tag: "2"

containerPort: 80

service:
  port: 80

ingress:
  name: ingress-hosts
  host: d3v0ps.duckdns.org
  path: "/"
  class: nginx

imagePullSecrets: dockerhub

maxSurge: 3
