replicaCount: 1

releaseName: react-site
namespace: prod

image:
  repository: registry.gitlab.com/dmakhalfeh/sample_websites
  tag: "1"

containerPort: 80

service:
  port: 80

ingress:
  name: ingress-hosts
  host: d3v0ps.duckdns.org
  path: "/"
  class: nginx

imagePullSecrets: registry-credentials

maxSurge: 3
